language: node_js

node_js:
  - '0.10'

branches:
  only:
    - master
    - travis-ci

# Not using `npm install --dev` because it is recursive. It will pull in the all
# development dependencies for CoffeeScript. Way too much spew in the Travis CI
# build output.

before_install:
  - npm install
  - npm install istanbul coveralls

env:
  global:
  - secure: qENMEK5TnNDzNvrTY1diAEyo2Dgs4BDWAuHUAyHpWDunRMfQNoLeVUPIFb7omNceSOh20InrO20pBWlGlkI9UItaS9NfeAzWsoWkEfsOzfEf1+R0G3B2ieIwVqOIeB9LlMSWCaR2K79zuk6F+EuUmNXv8QXO9/hLEIzvzEv1I7c=
